name: CI Release to Main

on:
  push:
    branches:
      - 'release/*'

permissions:
  contents: write
  pull-requests: write

jobs:
  validate-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Run Tests
        run: ./.github/scripts/check_test_success.sh

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Create PR to main
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PR_EXISTS=$(gh pr list --head "${{ github.ref_name }}" --base main --json number | jq 'length > 0')
          if [ "$PR_EXISTS" = "false" ]; then
            gh pr create --title "Merge release ${{ github.ref_name }} into main" \
                         --body "Automated release PR to main branch." \
                         --base main \
                         --head "${{ github.ref_name }}"
          else
            echo "PR already exists. Skipping creation."
          fi
